// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmyicxrelctjkmlsxbwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhteWljeHJlbGN0amttbHN4YndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDk5NzMsImV4cCI6MjA2MDIyNTk3M30.XtRHlz91DyMzIK6HcWR8IgDL6v2rct-kM8GvsNFvt6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);